server:
  port: 9001
spring:
  application:
    name: edge-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:9002/auths}
          predicates:
            - Path=/auths/**
          filters:
            - name: PreGatewayFilter
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/service-fallback
        - id: menu-service
          uri: ${MENU_SERVICE_URL:http://localhost:9003/menus}
          predicates:
            - Path=/menus/**
          filters:
            - name: PreGatewayFilter
            - name: CircuitBreaker
              args:
                name: menuCircuitBreaker
                fallbackUri: forward:/service-fallback
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:9004/orders}
          predicates:
            - Path=/orders/**
          filters:
            - name: PreGatewayFilter
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/service-fallback
        - id: delivery-service
          uri: ${DELIVERY_SERVICE_URL:http://localhost:9005/deliveries}
          predicates:
            - Path=/deliveries/**
          filters:
            - name: CircuitBreaker
              args:
                name: deliveryCircuitBreaker
                fallbackUri: forward:/service-fallback
        - id: chat-service
          uri: ${CHAT_SERVICE_URL:http://localhost:9006/chat}
          predicates:
            - Path=/chat/**
          filters:
            - name: PreGatewayFilter
            - name: CircuitBreaker
              args:
                name: chatCircuitBreaker
                fallbackUri: forward:/service-fallback
        - id: store-service
          uri: ${STORE_SERVICE_URL:http://localhost:9007/stores}
          predicates:
            - Path=/stores/**
          filters:
            - name: PreGatewayFilter
            - name: CircuitBreaker
              args:
                name: storeCircuitBreaker
                fallbackUri: forward:/service-fallback
        - id: ai-service
          uri: ${AI_SERVICE_URL:http://localhost:9008/api/ai}
          predicates:
            - Path=/ai/**
          filters:
            - name: PreGatewayFilter
            - name: CircuitBreaker
              args:
                name: aiCircuitBreaker
                fallbackUri: forward:/service-fallback

resilience4j:
  circuitbreaker:
    configs:
      default:
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
    instances:
      orderCircuitBreaker:
        base-config: default
        failure-rate-threshold: 70
        wait-duration-in-open-state: 20s
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 10s
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 5
    instances:
      orderCircuitBreaker:
        timeout-duration: 15s
sandit:
  auth-service-url: ${AUTH_SERVICE_URL:http://localhost:9002}