server:
  port: 9001
spring:
  application:
    name: edge-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9002/auths
          predicates:
            - Path=/auths/**
          filters:
            - name: PreGatewayFilter
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/service-fallback
        - id: menu-service
          uri: http://localhost:9003/menus
          predicates:
            - Path=/menus/**
          filters:
            - name: PreGatewayFilter
            - name: CircuitBreaker
              args:
                name: menuCircuitBreaker
                fallbackUri: forward:/service-fallback
        - id: order-service
          uri: http://localhost:9004/orders
          predicates:
            - Path=/orders/**
          filters:
            - name: PreGatewayFilter
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/service-fallback
        - id: dispatcher-service
          uri: http://localhost:9005/dispatchers
          predicates:
            - Path=/dispatchers/**
          filters:
            - name: CircuitBreaker
              args:
                name: dispatcherCircuitBreaker
                fallbackUri: forward:/service-fallback
#        - id: review-service
#          uri: http://localhost:9006/reviews
#          predicates:
#            - Path=/reviews/**
#          filters:
#            - name: PreGatewayFilter
#            - name: CircuitBreaker
#              args:
#                name: menuCircuitBreaker
#                fallbackUri: forward:/service-fallback
        - id: chat-service
          uri: http://localhost:9006/chat
          predicates:
            - Path=/chat/**
          filters:
            - name: PreGatewayFilter
            - name: CircuitBreaker
              args:
                name: chatCircuitBreaker
                fallbackUri: forward:/service-fallback



resilience4j:
  circuitbreaker:
    configs:
      default:
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 5
sandit:
  auth-service-url: http://localhost:9002
  dispatcher-service-url: http://localhost:9005