apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
spec:
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      nodeSelector:
        role: main
      containers:
        - name: edge-service
          image: 448049828702.dkr.ecr.ap-northeast-2.amazonaws.com/edge-service:latest #AWS 계정번호
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            requests:
              cpu: "300m"
              memory: "400Mi"
            limits:
              cpu: "500m"
              memory: "700Mi"
          ports:
            - containerPort: 9001
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:80
            - name: MENU_SERVICE_URL
              value: http://menu-service:80
            - name: ORDER_SERVICE_URL
              value: http://order-service:80
            - name: DELIVERY_SERVICE_URL
              value: http://delivery-service:80
            - name: CHAT_SERVICE_URL
              value: http://chat-service:80
            - name: STORE_SERVICE_URL
              value: http://store-service:80
            - name: AI_SERVICE_URL
              value: http://ai-service:80
